name: sensors_plus_linux
description: Sensors Plus for Linux
version: 0.1.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.20.0'

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: SensorsPlusLinuxPlugin

dependencies:
  flutter:
    sdk: flutter
  sensors_plus_platform_interface: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
