name: sensors_plus
description: Flutter plugin for accessing accelerometer and gyroscope sensors.
version: 0.6.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.sensors
        pluginClass: SensorsPlugin
      linux:
        default_package: sensors_plus_linux
      ios:
        pluginClass: FLTSensorsPlusPlugin
      web:
        default_package: sensors_plus_web

dependencies:
  flutter:
    sdk: flutter
  sensors_plus_web: ^0.2.0
  sensors_plus_platform_interface: ^0.2.0
  sensors_plus_linux: #^0.1.0
    path: ../sensors_plus_linux

dev_dependencies:
  test: ^1.3.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.9.2

environment:
  sdk: '>=2.1.0<3.0.0'
  flutter: '>=1.12.13+hotfix.5'
