name: battery_plus
description: Flutter plugin for accessing information about the battery state(full, charging, discharging).
version: 0.9.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.battery
        pluginClass: BatteryPlusPlugin
      ios:
        pluginClass: FLTBatteryPlusPlugin
      linux:
        dartPluginClass: BatteryLinux
        pluginClass: none
      macos:
        pluginClass: BatteryPlusMacosPlugin
      web:
        pluginClass: BatteryPlusPlugin
        fileName: src/web/battery_plus_web.dart
      windows:
        pluginClass: BatteryPlusWindowsPlugin

dependencies:
  dbus: ^0.1.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.0.5
  plugin_platform_interface: ^1.0.2

dev_dependencies:
  async: ^2.0.8
  mockito: ^4.1.2
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  test: ^1.3.0

environment:
  sdk: '>=2.1.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'
